DROP TABLE IF EXISTS favorites, transactions, mortgages, inspections, schools, listings, sellers, properties, buyers, neighborhoods, agents CASCADE;

CREATE TABLE agents(
    agent_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    email VARCHAR UNIQUE,
    phone VARCHAR,
    agency_name VARCHAR
);

CREATE TABLE neighborhoods(
    neighborhood_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    school_rating INT CHECK (school_rating BETWEEN 1 AND 10),
    air_quality_index FLOAT,
    crime_float FLOAT
);

CREATE TABLE buyers(
    buyer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    email VARCHAR UNIQUE,
    budget FLOAT,
    preferred_neighborhood_id INT REFERENCES neighborhoods(neighborhood_id) ON DELETE SET NULL
);

CREATE TABLE properties(
    property_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR,
    price FLOAT,
    bedrooms INT,
    bathrooms INT,
    area_sqft FLOAT,
    agent_id INT REFERENCES agents(agent_id) ON DELETE SET NULL
);

CREATE TABLE sellers(
    seller_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    email VARCHAR UNIQUE,
    property_id INT UNIQUE REFERENCES properties(property_id) ON DELETE SET NULL
);

CREATE TABLE listings(
    listing_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id INT REFERENCES properties(property_id) ON DELETE CASCADE,
    listing_date DATE,
    status VARCHAR CHECK (status IN ('available','sold'))
);

CREATE TABLE schools(
    school_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    rating INT CHECK (rating BETWEEN 1 AND 10),
    neighborhood_id INT REFERENCES neighborhoods(neighborhood_id) ON DELETE CASCADE
);

CREATE TABLE inspections(
    inspection_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id INT REFERENCES properties(property_id) ON DELETE CASCADE,
    buyer_id INT REFERENCES buyers(buyer_id) ON DELETE CASCADE,
    date DATE,
    feedback TEXT
);

CREATE TABLE mortgages(
    mortgage_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id INT REFERENCES buyers(buyer_id) ON DELETE CASCADE,
    property_id INT REFERENCES properties(property_id) ON DELETE CASCADE,
    loan_amount FLOAT,
    interest_rate FLOAT,
    term_years INT
);

CREATE TABLE transactions(
    transaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id INT REFERENCES buyers(buyer_id) ON DELETE CASCADE,
    property_id INT REFERENCES properties(property_id) ON DELETE CASCADE,
    amount FLOAT,
    date DATE
);

CREATE TABLE favorites(
    buyer_id INT REFERENCES buyers(buyer_id) ON DELETE CASCADE,
    property_id INT REFERENCES properties(property_id) ON DELETE CASCADE,
    PRIMARY KEY(buyer_id, property_id)
);
